### ISSUE TITLE
Location module warn

### ISSUE THREAD

**Issue by conscnt1** [zThana/RacesOfThana#8]
- Trying to delete location-module execute these warn:

```
[08:52:28 WARN]: java.lang.reflect.InvocationTargetException
[08:52:28 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:115)
[08:52:28 WARN]:        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.commands.base.BaseCommand.onCommand(BaseCommand.java:48)
[08:52:28 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[08:52:28 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:165)
[08:52:28 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:1000)
[08:52:28 WARN]:        at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:985)
[08:52:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:526)
[08:52:28 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:474)
[08:52:28 WARN]:        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1598)
[08:52:28 WARN]:        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1304)
[08:52:28 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330)
[08:52:28 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
[08:52:28 WARN]: Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getBoolean(String, boolean)" because "<parameter1>" is null
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.race.modules.ModuleEvents.<init>(ModuleEvents.java:13)
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.race.modules.location.LocationEvents.<init>(LocationEvents.java:16)
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.race.modules.location.LocationModule.<init>(LocationModule.java:29)
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.handlers.RaceSerializer.convertToRace(RaceSerializer.java:65)
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.handlers.RaceManager.refreshRaces(RaceManager.java:83)
[08:52:28 WARN]:        at RacesOfThana.jar//com.zthana.racesofthana.commands.RacesOfThanaCommand.reload(RacesOfThanaCommand.java:84)
[08:52:28 WARN]:        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[08:52:28 WARN]:        ... 12 more
```

**Comment by zThana** [comment]
This appears to have been the case for multiple modules. It will be fixed in the next update. Thank you!
